import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import "./globals.css";
import { StoryblokProvider } from "../components/StoryBlokProvider";
import Blog from "@/components/Blog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    blog: Blog,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
