import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import "./globals.css";
import { StoryblokProvider } from "../components/StoryBlokProvider";
import Blog from "@/components/Blog";
import Page from "@/components/Page";
import Link from "next/link";
import BackButton from "@/utils/back";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  return fetch(input, {
    ...init,
    cache: "no-cache",
  });
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
  components: {
    blog: Blog,
    page: Page,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#B4869F]`}
        >
          <header>
            <nav className="flex justify-between items-center p-4 bg-[#F2E9E4]">
              <Link href={"/"}>Home</Link>
              <Link href={"/blog"}>Blogs</Link>
              <Link href={"/"}>Create</Link>
            </nav>
            <BackButton />
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
